# vercel-merge.yml
name: Deploy to vercel on merge
on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: amondnet/vercel-action@v20
        with:
          vercel-token: "SUWuty2GYCY6wwaqrkHkZcbm"
          github-token: ${{ secrets.GITHUB_TOKEN }}
          vercel-args: '--prod'
          vercel-org-id: "team_p1C02aqWmCE3yAHeOC41DdHX"
          vercel-project-id: "prj_MUiHq0pcmdOAcSqnxS5w5T0S3sI6"
